import {
  AbortCampaignParamsSchema,
  ActivateTriggeredCampaignParamsSchema,
  ArchiveCampaignsParamsSchema,
  CancelCampaignParamsSchema,
  CreateBlastCampaignParamsSchema,
  CreateTriggeredCampaignParamsSchema,
  DeactivateTriggeredCampaignParamsSchema,
  GetCampaignMetricsParamsSchema,
  GetCampaignParamsSchema,
  GetCampaignsParamsSchema,
  GetChildCampaignsParamsSchema,
  ScheduleCampaignParamsSchema,
  SendCampaignParamsSchema,
  TriggerCampaignParamsSchema,
} from "@iterable/api";

import { sortTransform } from "./transforms.js";
import type { CommandDefinition } from "./types.js";
import { defineCommand } from "./types.js";

export const campaignCommands: CommandDefinition[] = [
  defineCommand({
    category: "campaigns",
    name: "list",
    description: "Retrieve campaigns",
    clientMethod: "getCampaigns",
    schema: GetCampaignsParamsSchema,
    cliTransforms: { sort: sortTransform },
  }),
  defineCommand({
    category: "campaigns",
    name: "get",
    description: "Get detailed information about a specific campaign",
    clientMethod: "getCampaign",
    schema: GetCampaignParamsSchema,
  }),
  defineCommand({
    category: "campaigns",
    name: "get-metrics",
    description: "Get campaign performance metrics",
    clientMethod: "getCampaignMetrics",
    schema: GetCampaignMetricsParamsSchema,
  }),
  defineCommand({
    category: "campaigns",
    name: "create-blast",
    description:
      "Create a new blast campaign from an existing template. The campaign is created without being scheduled. Use schedule to schedule it for delivery.",
    clientMethod: "createBlastCampaign",
    schema: CreateBlastCampaignParamsSchema,
  }),
  defineCommand({
    category: "campaigns",
    name: "create-triggered",
    description:
      "Create a new triggered campaign from an existing template. The campaign is created in Ready state and must be activated before it can send.",
    clientMethod: "createTriggeredCampaign",
    schema: CreateTriggeredCampaignParamsSchema,
  }),
  defineCommand({
    category: "campaigns",
    name: "get-children",
    description: "Get child campaigns generated by a recurring campaign",
    clientMethod: "getChildCampaigns",
    schema: GetChildCampaignsParamsSchema,
    cliTransforms: { sort: sortTransform },
  }),
  defineCommand({
    category: "campaigns",
    name: "schedule",
    description: "Schedule an existing campaign to be sent at a specific time",
    clientMethod: "scheduleCampaign",
    schema: ScheduleCampaignParamsSchema,
  }),
  defineCommand({
    category: "campaigns",
    name: "abort",
    description: "Abort a campaign that is currently running",
    clientMethod: "abortCampaign",
    schema: AbortCampaignParamsSchema,
  }),
  defineCommand({
    category: "campaigns",
    name: "cancel",
    description: "Cancel a scheduled or recurring campaign",
    clientMethod: "cancelCampaign",
    schema: CancelCampaignParamsSchema,
  }),
  defineCommand({
    category: "campaigns",
    name: "activate",
    description: "Activate a triggered campaign",
    clientMethod: "activateTriggeredCampaign",
    schema: ActivateTriggeredCampaignParamsSchema,
  }),
  defineCommand({
    category: "campaigns",
    name: "deactivate",
    description: "Deactivate a triggered campaign",
    clientMethod: "deactivateTriggeredCampaign",
    schema: DeactivateTriggeredCampaignParamsSchema,
  }),
  defineCommand({
    category: "campaigns",
    name: "archive",
    description:
      "Archive one or more campaigns. Scheduled/recurring campaigns will be cancelled, running campaigns will be aborted.",
    clientMethod: "archiveCampaigns",
    schema: ArchiveCampaignsParamsSchema,
  }),
  defineCommand({
    category: "campaigns",
    name: "trigger",
    description: "Trigger a campaign to send to specified lists",
    clientMethod: "triggerCampaign",
    schema: TriggerCampaignParamsSchema,
  }),
  defineCommand({
    category: "campaigns",
    name: "send",
    description: "Send an existing scheduled campaign immediately",
    clientMethod: "sendCampaign",
    schema: SendCampaignParamsSchema,
  }),
];
